### ISSUE TITLE
Inventory shouldn't write over Trend Report when it's displayed

### ISSUE THREAD

**Issue by Sam-Amara** [atomicxistence/MSSA_Exercise_4A#14]
I was viewing trend report and bought ores from the current planet's market. I was surprised to see the inventory list populate on top of the report. It could a good or bad thing, however.

**Comment by jeff-adams** [comment]
I can't recreate this bug

**Comment by Sam-Amara** [comment]
I was able to reproduce this again, while both buying and selling items with Trend Report displayed

**Comment by Sam-Amara** [comment]
fixed, bug was introduced when implementing upgrades
